### ISSUE TITLE
Is this going to be updated any time soon?

### ISSUE THREAD

**Issue by slambo311** [gkjohnson/source-engine-model-loader#19]
It's pretty much dead right now, any plans of reviving it?

**Comment by gkjohnson** [comment]
Hello! I currently have no plans to update, add features to, or publish this project. I'm happy to take contributions though if you'd like to update it to the latest version of three.js yourself or add any new capabilities!

**Comment by MesaBlack** [comment]
make this load models from files!

**Comment by gkjohnson** [comment]
> make this load models from files!

I won't be tolerating continued demands for free work to features or spam on irrelevant issues. As has already been stated you can contribute a PR to for the drag and drop feature if you'd like to see it added.

**Comment by MesaBlack** [comment]
where is that PR?

**Comment by MesaBlack** [comment]
oh... pull request.
